from datetime import datetime
from typing import Dict, Any, Optional
import uuid
from meeting_os.lib.tenancy.vault_context import TenantContext
from meeting_os.lib.db import db
import logging

# Configure local logger for fallback
logger = logging.getLogger("EventLog")

class EventLog:
    """Supabase-backed Append-Only Event Log"""
    
    def __init__(self, db_client=None):
        # Allow injection, defaut to global db
        self.db = db_client or db
    
    def log(self, event: Dict[str, Any]):
        """Persist event to Supabase event_logs table"""
        
        # 1. Resolve Context
        try:
            vault_id = TenantContext.get_vault()
            user_id = TenantContext.get_user()
        except RuntimeError:
            vault_id = event.get("vault_id", "unknown_vault")
            user_id = event.get("user_id", "system")
            
        # 2. Construct Record
        event_record = {
            # "id": Generated by DB (uuid_generate_v4)
            "timestamp": datetime.utcnow().isoformat(),
            "event_type": event["type"],
            "severity": event.get("severity", "info"),
            "vault_id": vault_id,
            "user_id": user_id,
            "workflow_id": event.get("workflow_id"),
            "payload": event.get("payload", {}),
            "metadata": event.get("metadata", {})
        }
        
        # 3. Write to Supabase (Async/Fire-and-forget in production, sync here)
        try:
            if self.db.client:
                self.db.table("event_logs").insert(event_record).execute()
                # logger.info(f"Logged {event['type']} to Supabase")
            else:
                logger.warning("Supabase client missing. Event logged to stdout only.")
                print(f"[EVENT_LOG] {event_record}")
        except Exception as e:
            logger.error(f"Failed to log event to Supabase: {e}")
            print(f"[EVENT_LOG_FAIL] {event_record} Error: {e}")
            
        return True
