-- Protocol Version 1.0 (Ultrathink)
-- Enable extensions
CREATE EXTENSION IF NOT EXISTS vector;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. EVENT LOGS (Append-Only)
-- Stores the raw immutable history of what happened in the system.
CREATE TABLE IF NOT EXISTS event_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    timestamp TIMESTAMPTZ DEFAULT NOW (),
    event_type TEXT NOT NULL, -- e.g. "meeting.processed", "tool.used"
    severity TEXT DEFAULT 'info', -- info, warning, error, critical
    vault_id TEXT NOT NULL, -- Tenant ID
    user_id TEXT, -- Who triggered it (if known)
    workflow_id TEXT, -- Trace ID for distributed events
    payload JSONB NOT NULL, -- Structured event data
    metadata JSONB -- Extra tags (server version, region)
);

-- Index for fast queries by vault and type
CREATE INDEX IF NOT EXISTS idx_event_logs_vault_type_time ON event_logs (
    vault_id,
    event_type,
    timestamp DESC
);

-- 2. UNIVERSAL CONTEXT OBJECTS (The Nervous System)
-- Stores the standardized "Situation Reports" generated by Router/Agents.
CREATE TABLE IF NOT EXISTS universal_context_objects (
    event_id TEXT PRIMARY KEY, -- e.g. "mtg_2026_01_31_fireflies_123"
    source TEXT NOT NULL, -- Fireflies, Slack, WhatsApp
    created_at TIMESTAMPTZ DEFAULT NOW (),
    routing_flags JSONB NOT NULL, -- { "sales": true, "product": false ... }
    context_layer JSONB NOT NULL, -- { "summary": "...", "sentiment": "..." }
    raw_data JSONB, -- The original webhook payload (for replay)
    status TEXT DEFAULT 'processed' -- processing, processed, failed
);

-- 3. DAILY USAGE (The Cost Controller)
-- Tracks token usage and spend per vault per day.
CREATE TABLE IF NOT EXISTS daily_usage (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
    date DATE DEFAULT CURRENT_DATE,
    vault_id TEXT NOT NULL,
    model TEXT NOT NULL, -- gemini-1.5-flash, gemini-1.5-pro
    input_tokens BIGINT DEFAULT 0,
    output_tokens BIGINT DEFAULT 0,
    cost_usd NUMERIC(10, 6) DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW (),
    UNIQUE (date, vault_id, model)
);

-- 4. IDEMPOTENCY LOCKS
-- Prevents double-execution of workflows.
CREATE TABLE IF NOT EXISTS workflow_locks (
    lock_key TEXT PRIMARY KEY, -- Hashed "workflow:idempotency_key"
    created_at TIMESTAMPTZ DEFAULT NOW (),
    expires_at TIMESTAMPTZ NOT NULL,
    status TEXT DEFAULT 'acquired' -- acquired, completed, failed
);